export default function MedicalDisclaimer() {
    return (
        <div className="text-[10px] sm:text-xs text-slate-400 mt-2 px-1">
            <p>
                <strong>Med24 AI Disclaimer:</strong> This response is generated by artificial intelligence and does not constitute professional medical advice, diagnosis, or treatment. Always consult your physician.
            </p>
        </div>
    );
}
